### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by akashbahai** [Tan-group/cgRNASP#1]
Hi,
Thanks for providing the code to your tool. However, I am not able to get it running on my system. 
I am getting 'Segmentation fault (core dumped)' error. What could be the cause of this error?
I have already tried running the precompiled binaries as well as locally compiled binaries.
I am using Ubuntu 20.04.

**Comment by louen123** [comment]
I can't exactly catch your question. But I can give your some advice.
You can download and extract the file cgRNASP.
cd cgRNASP/cgRNASP/example/
sudo chmod 777 cgRNASP
bash run_batch.sh
then you can get the result file.

The following step show how to compile cgRNASP.c. Maybe you miss the -lm.
# Compilation

 gcc cgRNASP.c -lm -o cgRNASP

**Comment by Tan-group** [comment]
> Hi, Thanks for providing the code to your tool. However, I am not able to get it running on my system. I am getting 'Segmentation fault (core dumped)' error. What could be the cause of this error? I have already tried running the precompiled binaries as well as locally compiled binaries. I am using Ubuntu 20.04.

Hi, Akash. Thanks for using our tool and giving the feedback.
The "Segmentation fault (core dumped)" error might be not related to the version of ubuntu. And this type of error occurs when the program attempts to access a memory address that is not allowed to be accessed.
I'm guessing it was because, the subfolder "data/" and compiled "cgRNASP" were not be in the same folder. So the files in the "data/" folder could not be correctly loaded.

**Comment by akashbahai** [comment]
Hi,
Thanks for your response. I have tried running the program in Linux and Mac environments. I am still getting the same Segmentation fault (core dumped) error.
I have compiled the cgRNASP binary file using the 'gcc cgRNASP.c -lm -o cgRNASP' command. I have tried running from inside the example folder as well as the cgRNASP folder (data/) folder is present in both. I am still getting the same problem.
![screenshot](https://user-images.githubusercontent.com/5026918/231120637-31493f94-3100-47d6-8f16-daeea575d07a.png)

**Comment by Tan-group** [comment]
> Hi, Thanks for your response. I have tried running the program in Linux and Mac environments. I am still getting the same Segmentation fault (core dumped) error. I have compiled the cgRNASP binary file using the 'gcc cgRNASP.c -lm -o cgRNASP' command. I have tried running from inside the example folder as well as the cgRNASP folder (data/) folder is present in both. I am still getting the same problem. ![screenshot](https://user-images.githubusercontent.com/5026918/231120637-31493f94-3100-47d6-8f16-daeea575d07a.png)

Hi, Akash. Thanks for your immediate feedback.

According to the picture you showed, we found that the parameters passed into the program from the terminal were not meet the needs of our program.
You can try the following command "./cgRNASP example/ 2 output.txt".
The first parameter specifies the route of the folder that containg all pdb files you want to score. (It can be convenient to score a batch of pdb files.)
The second one specifis the total number of pdb files in that route. (If there is only one file, you can also use "1" to occupy this position. Notably, the specified number must be greater than or equal to the actual number of pdb files.)
The final one specifies the output file.
![image](https://user-images.githubusercontent.com/82859325/231146785-a123490d-960b-47a0-940a-fb1d607c174c.png)
![image](https://user-images.githubusercontent.com/82859325/231146921-cdbc6d3c-d3aa-4ef2-b139-08bd36572465.png)

You can also refer to the "run_batch.sh" file.
 
Looking forward to the successful running.

**Comment by akashbahai** [comment]
Hi,
Thanks for your response. The tool is running for me now.
